# ============================================================================
# GitHub Actions Runner - CI/CD Self-Hosted Runner
# ============================================================================
# Profile: cicd, all
# Networks: internal
# WARNING: Has Docker socket access - significant privileges
# ============================================================================

services:
  github-runner:
    profiles: ["cicd", "all"]
    image: actions-runner:custom
    container_name: github-runner
    restart: unless-stopped

    # Environment
    environment:
      - TZ=Europe/Madrid

    # Volumes
    volumes:
      # Docker socket - allows runner to execute docker commands
      # WARNING: This grants significant privileges - use with caution
      - /var/run/docker.sock:/var/run/docker.sock

      # Homeserver directory - for deployment scripts
      # TODO: Consider limiting to specific subdirectories for security
      - /opt/homeserver:/opt/homeserver

      # Runner installation with credentials (pre-configured)
      - /opt/homeserver/services/github-runner:/runner

    # Working directory
    working_dir: /runner

    # Command
    command: ./run.sh

    # Networks
    networks:
      - internal

    # Health check - check if runner process is active
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep -f 'Runner.Listener' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

    # Security
    security_opt:
      - no-new-privileges:true

    # Labels
    labels:
      - "com.homeserver.group=automation"
      - "com.homeserver.description=GitHub Actions self-hosted runner"
