# ============================================================================
# Authelia - SSO Authentication Server
# ============================================================================
# Dependencies: postgres-auth, redis-auth, openldap
# Networks: internal (backend), proxy (forward auth)
# ============================================================================

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped

    # Environment variables
    environment:
      - TZ=${TZ}
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/redis_password

    # Docker secrets
    secrets:
      - postgres_password
      - redis_password

    # Volumes
    volumes:
      # Configuration file
      - ../../services/auth/authelia/configuration.yml:/config/configuration.yml:ro

    # Networks - CRITICAL: Must be on BOTH networks
    networks:
      - internal   # Connect to postgres-auth, redis-auth, openldap
      - proxy      # Connect to Caddy for forward auth

    # Depends on database and cache
    depends_on:
      postgres-auth:
        condition: service_healthy
      redis-auth:
        condition: service_healthy

    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    # Security
    security_opt:
      - no-new-privileges:true

    # Labels
    labels:
      - "com.homeserver.group=auth"
      - "com.homeserver.description=Authelia SSO authentication server"

# ============================================================================
# Docker Secrets
# ============================================================================
secrets:
  postgres_password:
    file: ../../secrets/postgres_password.txt
  redis_password:
    file: ../../secrets/redis_password.txt
