# ============================================================================
# User Management API - Backend for User Registration
# ============================================================================
# Backend API for user registration and management with LDAP
# Dependencies: redis-auth, openldap
# Networks: internal (backend), proxy (accessed via Caddy)
# ============================================================================

services:
  user-management:
    image: ghcr.io/mykyta-home-server/user-management-api:latest
    container_name: user-management
    restart: unless-stopped

    # Environment variables
    environment:
      # Redis configuration (for invitation tokens)
      - REDIS_HOST=redis-auth
      - REDIS_PORT=6379
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password

      # LDAP configuration (for user credentials)
      - LDAP_SERVER=openldap
      - LDAP_PORT=389
      - LDAP_ADMIN_DN=cn=admin,dc=mykyta-ryasny,dc=dev
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_BASE_DN=dc=mykyta-ryasny,dc=dev

      # Application configuration
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${USER_MANAGEMENT_JWT_SECRET}
      - TZ=${TZ}

    # Docker secrets
    secrets:
      - redis_password

    # Networks - internal for backend, proxy for Caddy reverse proxy
    networks:
      - internal
      - proxy

    # Depends on
    depends_on:
      openldap:
        condition: service_healthy
      redis-auth:
        condition: service_healthy

    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    # Security
    security_opt:
      - no-new-privileges:true

    # Labels
    labels:
      - "com.homeserver.group=authentication"
      - "com.homeserver.description=User Management API for LDAP"

# ============================================================================
# Docker Secrets
# ============================================================================
secrets:
  redis_password:
    file: ../../secrets/redis_password.txt
