services:
  github-runner:
    image: actions-runner:custom
    container_name: github-runner
    restart: unless-stopped

    environment:
      # Timezone
      - TZ=Europe/Madrid

    volumes:
      # Docker socket - allows runner to execute docker commands
      - /var/run/docker.sock:/var/run/docker.sock

      # Homeserver directory - for deployment scripts
      - /opt/homeserver:/opt/homeserver

      # Runner installation with credentials (pre-configured)
      - /opt/homeserver/services/github-runner:/runner

    working_dir: /runner
    command: ./run.sh

    networks:
      - internal

    security_opt:
      - no-new-privileges:true

    labels:
      - "com.homeserver.group=automation"
      - "com.homeserver.description=GitHub Actions self-hosted runner for all repos"
