# ============================================================================
# Monitoring Stack - Docker Compose Configuration
# ============================================================================
# Services: Loki, Promtail, Grafana, Uptime Kuma
# Networks: monitoring (logs), internal (backend), proxy (frontend)
#
# Architecture:
#   Promtail → Loki → Grafana (log aggregation)
#   Uptime Kuma → Internal services (uptime monitoring)
# ============================================================================

services:
  # ==========================================================================
  # Loki - Log aggregation system
  # ==========================================================================
  loki:
    profiles: ["monitoring", "all"]
    image: grafana/loki:3.0.0
    container_name: loki
    restart: unless-stopped

    # Networks
    networks:
      - monitoring  # Promtail → Loki communication
      - internal    # Other services can query logs

    # Volumes
    volumes:
      - ../services/monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - ../services/monitoring/loki/data:/loki

    # Command
    command: -config.file=/etc/loki/local-config.yaml

    # Security
    security_opt:
      - no-new-privileges:true

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    # Labels
    labels:
      - "com.homeserver.group=monitoring"
      - "com.homeserver.description=Log aggregation system"

  # ==========================================================================
  # Promtail - Log collector
  # ==========================================================================
  promtail:
    profiles: ["monitoring", "all"]
    image: grafana/promtail:3.0.0
    container_name: promtail
    restart: unless-stopped

    # Networks - SECURITY FIX: Add internal for better service discovery
    networks:
      - monitoring  # Connect to Loki
      - internal    # Service discovery

    # Volumes
    volumes:
      - ../services/monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ../services/monitoring/promtail/positions:/tmp/positions

    # Command
    command: -config.file=/etc/promtail/config.yml

    # Health check - check if promtail process is running
    healthcheck:
      test: ["CMD-SHELL", "pgrep promtail || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Security
    security_opt:
      - no-new-privileges:true

    # Depends on
    depends_on:
      loki:
        condition: service_healthy

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

    # Labels
    labels:
      - "com.homeserver.group=monitoring"
      - "com.homeserver.description=Log collection agent"

  # ==========================================================================
  # Grafana - Visualization and dashboards
  # ==========================================================================
  grafana:
    profiles: ["monitoring", "all"]
    image: grafana/grafana:10.2.2
    container_name: grafana
    restart: unless-stopped

    # Networks
    networks:
      - monitoring  # Connect to Loki
      - internal    # Connect to internal services
      - proxy       # Connect to Caddy for external access

    # Volumes
    volumes:
      - ../services/monitoring/grafana/data:/var/lib/grafana
      - ../services/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ../services/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro

    # Environment variables
    environment:
      # Security - SHOULD BE IN .env FILE
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}  # TODO: Set in .env

      # Server settings
      - GF_SERVER_ROOT_URL=https://monitor.mykyta-ryasny.dev
      - GF_SERVER_DOMAIN=monitor.mykyta-ryasny.dev

      # Disable analytics
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false

    # User - Run as grafana user (non-root)
    user: "472:472"

    # Security
    security_opt:
      - no-new-privileges:true

    # Depends on
    depends_on:
      loki:
        condition: service_healthy

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    # Labels
    labels:
      - "com.homeserver.group=monitoring"
      - "com.homeserver.description=Monitoring and visualization platform"
