services:
  # Caddy - Reverse proxy with automatic HTTPS
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../services/proxy/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ../services/proxy/caddy/sites:/etc/caddy/sites:ro
      - ../services/proxy/caddy/data:/data
      - ../services/proxy/caddy/config:/config
      - ../services/proxy/caddy/certs:/etc/caddy/certs:ro
    networks:
      - internal  # Connect to internal services
      - proxy     # External-facing

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "curl -kf https://localhost/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

