services:
  # Uptime Kuma - Service monitoring dashboard
  uptime-kuma:
    profiles: ["monitoring", "all"]
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped

    # Volumes
    volumes:
      - ../services/monitoring/uptime-kuma:/app/data

    # Networks
    networks:
      - internal
      - monitoring

    # Ports (internal only - accessed via Caddy reverse proxy)
    ports:
      - "3001:3001"

    # Health check
    healthcheck:
      test: ["CMD", "node", "extra/healthcheck.js"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

    # Security
    security_opt:
      - no-new-privileges:true

    # Labels
    labels:
      - "com.homeserver.group=monitoring"
      - "com.homeserver.description=Uptime Kuma monitoring dashboard"
