services:
  user-management:
    profiles: ["all"]
    image: ghcr.io/mykyta-home-server/user-management-api:latest
    container_name: user-management
    restart: unless-stopped

    environment:
      # Redis configuration (for invitation tokens)
      - REDIS_HOST=redis-auth
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

      # LDAP configuration (for user credentials)
      - LDAP_SERVER=openldap
      - LDAP_PORT=389
      - LDAP_ADMIN_DN=cn=admin,dc=mykyta-ryasny,dc=dev
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_BASE_DN=dc=mykyta-ryasny,dc=dev

      # Application configuration
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${USER_MANAGEMENT_JWT_SECRET}
      - TZ=${TZ}

    networks:
      - internal
      - proxy

    depends_on:
      - openldap
      - redis-auth

    labels:
      - "com.homeserver.group=authentication"
      - "com.homeserver.description=User Management API"
