services:
  # Watchtower - Automatic Docker container updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      # Check for updates every 24 hours (86400 seconds)
      - WATCHTOWER_POLL_INTERVAL=86400

      # MONITOR ONLY - Do not auto-update (security best practice)
      - WATCHTOWER_MONITOR_ONLY=true

      # Send notifications when updates are available
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}

      # Clean up old images after updating (disabled in monitor mode)
      - WATCHTOWER_CLEANUP=true

      # Only monitor containers with the label "com.centurylinklabs.watchtower.enable=true"
      - WATCHTOWER_LABEL_ENABLE=true

      # Include containers that are restarting
      - WATCHTOWER_INCLUDE_RESTARTING=true

      # Debug mode
      - WATCHTOWER_DEBUG=false

      # Docker API version (use a compatible version)
      - DOCKER_API_VERSION=1.44
    volumes:
      # Access to Docker socket to manage containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount Docker credentials for private registry access
      - /home/mykyta/.docker/config.json:/config.json:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Don't update watchtower itself
