# ============================================================================
# Maintenance Cron - Dockerized Scheduled Tasks
# ============================================================================
# Containerized cron for scheduled maintenance tasks
# Logs to stdout (captured by Promtail → Loki → Grafana)
# Profile: maintenance, all
# ============================================================================

services:
  # ==========================================================================
  # Maintenance Cron - Scheduled tasks container
  # ==========================================================================
  maintenance-cron:
    profiles: ["maintenance", "all"]
    image: alpine:3.22
    container_name: maintenance-cron
    restart: unless-stopped

    # Environment
    environment:
      - TZ=Europe/Madrid
      # Jellyfin authentication (API key - required for OIDC/SSO setup)
      - JELLYFIN_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY:-}
      # Media stack APIs (for cleanup script)
      - JELLYSEERR_URL=http://jellyseerr:5055
      - JELLYSEERR_API_KEY=${JELLYSEERR_API_KEY:-}
      - RADARR_URL=http://radarr:7878
      - SONARR_URL=http://sonarr:8989
      - QBITTORRENT_URL=http://qbittorrent:8080
      - RADARR_API_KEY=${RADARR_API_KEY:-}
      - SONARR_API_KEY=${SONARR_API_KEY:-}
      # Set to 'false' to enable actual deletions (default: dry run)
      - DRY_RUN=${MEDIA_CLEANUP_DRY_RUN:-true}

    # Volumes
    volumes:
      # Mount scripts directory (read-only)
      - ../../scripts:/scripts:ro
      # Mount crontab configuration (at different location to avoid conflicts)
      - ../../services/maintenance/cron/crontab:/crontab-source:ro
      # Mount entrypoint script
      - ../../services/maintenance/cron/entrypoint.sh:/entrypoint.sh:ro
      # Mount media data for cleanup scripts (to verify files exist)
      - ../../data/media:/data/media:ro
      # Docker socket for container operations (backup script)
      - /var/run/docker.sock:/var/run/docker.sock:ro

    # Networks
    networks:
      - internal  # Access to Jellyfin and other services
      - monitoring  # Logs collected by Promtail

    # Use entrypoint script to setup and run crond
    command: ["/entrypoint.sh"]

    # Health check - verify cron is running
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep crond || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Security
    security_opt:
      - no-new-privileges:true

    # Labels for Promtail
    labels:
      - "com.homeserver.group=maintenance"
      - "com.homeserver.description=Dockerized cron for scheduled maintenance"
      - "logging=promtail"  # Promtail will collect these logs
